name: pulser_sdk
description: Secure multi-channel notification SDK. Push, inbox, in-app, events, preferences.
version: 1.0.0
repository: https://github.com/levinkm/pulser-flutter-sdk
homepage: https://github.com/levinkm/pulser-flutter-sdk

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^3.0.3
  http: ^1.1.0
  flutter_secure_storage: ^10.3.1
  crypto: ^3.0.0
  connectivity_plus: ^6.1.5
  google_api_availability: ^5.0.1
  device_info_plus: ^10.0.0
  package_info_plus: ^8.0.0
  uuid: ^4.0.0

flutter:
  plugin:
    platforms:
      ios:
        classPrefix: Pulser
        pluginClass: PulserPlugin
        sharedDarwinSource: false

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
